kind: pipeline
name: Installation

# Configuration
volumes:
  - name: cache
    host: 
      path: /tmp/cache

steps:

# Restore cache
- name: Restore Installation Cache
  image: drillster/drone-volume-cache
  pull: if-not-exists
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - node_modules
  trigger:
    branch:
    - main
    
# Install the app
- name: Install the app
  image: node:lts-buster
  pull: if-not-exists
  commands: 
  - npm install
  - npm run build
  trigger:
    branch:
    - main

# Rebuild cache
- name: Build Installation Cache
  image: drillster/drone-volume-cache
  pull: if-not-exists
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - node_modules
  trigger:
    branch:
    - main

# Clean up 
- name: Clean up
  image: alpine
  pull: if-not-exists
  commands: 
  - mkdir /drone/tmp
  - mv /drone/src/* /drone/tmp
  - mv /drone/tmp/build/* /drone/src
  - rm -rf web_modules _dist_ __snowpack__
  - sed -i 's|src="/js/|src="./js/|g' index.html
  trigger:
    branch:
    - main

# Transfer to the server
- name: Transfer Source
  image: appleboy/drone-scp
  pull: if-not-exists
  settings: 
    host:
      from_secret: scp_host
    user: 
      from_secret: scp_user
    key:
      from_secret: scp_key
    source: 
      - '*'
      - '.*'
    target: '/var/www/tools.repair.wiki/prod/editor'
    rm: true
    trigger:
      branch:
      - main
