kind: pipeline
name: Installation

steps:

- name: Install the app
  image: node:lts-buster
  pull: if-not-exists
  settings: 
    commands:
    - npm install
    - npm run build
    - mkdir /drone/tmp
    - mv /drone/src/* /drone/tmp
    - mv /drone/tmp/build/* /drone/src
    - rm -rf web_modules _dist_ __snowpack__

- name: Transfer Source
  image: appleboy/drone-scp
  pull: if-not-exists
  settings: 
    host:
      from_secret: scp_host
    user: 
      from_secret: scp_user
    password:
      from_secret: scp_password
    source: 
      - '*'
      - '.*'
    target: '/var/www/products/repair-caption-search.zierhut-it.de/prod/editor'
    rm: true
    trigger:
      branch:
      - master