kind: pipeline
name: Installation

# Configuration
volumes:
  - name: cache
    host: 
      path: /tmp/cache

steps:

# Restore cache
- name: Restore Installation Cache
  image: drillster/drone-volume-cache
  pull: if-not-exists
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - node_modules

# Install the app
- name: Install the app
  image: node:lts-buster
  pull: if-not-exists
  commands: 
  - npm install
  - npm run build
  - mkdir /drone/tmp
  - mv /drone/src/* /drone/tmp
  - mv /drone/tmp/build/* /drone/src
  - rm -rf web_modules _dist_ __snowpack__
  - sed -i 's|src="/js/|src="./js/|g' index.html

# Rebuild cache
- name: Build Installation Cache
  image: drillster/drone-volume-cache
  pull: if-not-exists
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - node_modules

- name: Transfer Source
  image: appleboy/drone-scp
  pull: if-not-exists
  settings: 
    host:
      from_secret: scp_host
    user: 
      from_secret: scp_user
    password:
      from_secret: scp_password
    source: 
      - '*'
      - '.*'
    target: '/var/www/products/repair-caption-search.zierhut-it.de/prod/editor'
    rm: true
    trigger:
      branch:
      - master